version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - suceco-db-api-dev

  suceco-db-api-dev:
    image: postgres:13-alpine
    container_name: suceco-db-api-dev
    restart: always
    volumes:
      - dev-suceco-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  dev-suceco-db-data:



