version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=false
    expose:
      - 8000
    volumes:
      - ./app:/app
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 app.wsgi"
    env_file:
      - .env.prod
    depends_on:
      - suceco-db-api

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app

  suceco-db-api:
    image: postgres:13-alpine
    container_name: suceco-db-api
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  dev-db-data:



