version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=false
        - SECRET_KEY=${SECRET_KEY}
    restart: always
    expose:
      - 8000
    volumes:
      - ./app:/app
      - prod-suceco-static-data:/vol/static
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 app.wsgi"
    env_file:
        - .env
    depends_on:
      - suceco-db-api

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
    volumes_from:
      - app

  suceco-db-api:
    image: postgres:13-alpine
    container_name: suceco-db-api
    restart: always
    volumes:
      - prod-suceco-db-data:/var/lib/postgresql/data.prod
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  prod-suceco-db-data:
  prod-suceco-static-data:



