# Generated by Django 4.1.4 on 2023-01-02 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2023, 1, 2, 3, 54, 33, 634444, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
