# Generated by Django 4.1.5 on 2023-01-04 04:10

from django.db import migrations, models
import enumchoicefield.fields
import utils.constants


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('domain', enumchoicefield.fields.EnumChoiceField(enum_class=utils.constants.DomainsType, max_length=14)),
                ('status', enumchoicefield.fields.EnumChoiceField(default=utils.constants.StatusType(1), enum_class=utils.constants.StatusType, max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
