# Generated by Django 4.1.5 on 2023-01-07 03:03

from django.db import migrations, models
import enumfields.fields
import utils.constants


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('domain', enumfields.fields.EnumIntegerField(enum=utils.constants.DomainType)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
