# Generated by Django 4.1.4 on 2023-01-04 00:59

from django.db import migrations, models
import utils.constants


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('domain', models.CharField(choices=[(utils.constants.DomainsType['AMAZONIA'], 'Amazonia'), (utils.constants.DomainsType['MATA_ATLANTICA'], 'Mata Atlantica'), (utils.constants.DomainsType['CAATINGA'], 'Caatinga'), (utils.constants.DomainsType['CERRADO'], 'Cerrado'), (utils.constants.DomainsType['PANTANAL'], 'Pantanal'), (utils.constants.DomainsType['PRADARIA'], 'Pradaria')], max_length=100)),
                ('status', models.IntegerField(choices=[(utils.constants.StatusType['ACTIVE'], 'Active'), (utils.constants.StatusType['INACTIVE'], 'Inactive')], default=utils.constants.StatusType['ACTIVE'])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
