# Generated by Django 4.1.5 on 2023-01-12 01:24

from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import utils.constants


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_forest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publication', models.CharField(default='', max_length=1000, unique=True)),
                ('url', models.CharField(default='', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(help_text='Species', max_length=1000, unique=True)),
            ],
            options={
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('stage', enumfields.fields.EnumIntegerField(enum=utils.constants.StageType)),
                ('state', enumfields.fields.EnumIntegerField(enum=utils.constants.StateType)),
                ('forest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forest')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reference')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.species')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
