# Generated by Django 4.1.5 on 2023-01-21 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reference_species_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterPicture',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core.register')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
