---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout the Code
        uses: actions/checkout@v2
      - name: Build
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
      - name: Test the Code
        run: sleep 30 && docker ps &&
             docker-compose run --rm app sh -c "python manage.py wait_for_db &&
                                                python manage.py test --keepdb"
      - name: Lint the Code
        run: docker-compose run --rm app sh -c "flake8"





